# Generated by Django 4.1.1 on 2022-09-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=160)),
                ('cover_image', models.ImageField(upload_to='media/uploads/photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('first_image', models.ImageField(upload_to='media/uploads/photos/')),
                ('second_image', models.ImageField(upload_to='media/uploads/photos/')),
            ],
        ),
    ]
