# Generated by Django 4.1.1 on 2022-09-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_pub',
            field=models.DateField(auto_now=True, verbose_name='Date Published'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.CharField(max_length=160, verbose_name='Article Title'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(upload_to='media/uploads/photos/', verbose_name='Cover Image'),
        ),
    ]
