# Generated by Django 4.1.1 on 2022-09-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_article_date_pub_paragraph_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph',
            field=models.ManyToManyField(to='home.paragraph'),
        ),
    ]
