# Generated by Django 4.1.1 on 2022-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_article_paragraph_paragraph_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_description',
            field=models.TextField(default='F', max_length=360, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='paragraph',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
    ]
