# Generated by Django 4.1.1 on 2022-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_article_article_description_paragraph_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_description',
            field=models.TextField(max_length=360, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='order',
            field=models.IntegerField(verbose_name='Order'),
        ),
    ]
