# Generated by Django 4.1.1 on 2022-09-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_article_article_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_description',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
    ]
