# Generated by Django 4.1.1 on 2022-09-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_article_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(upload_to='uploads/photos/', verbose_name='Cover Image'),
        ),
    ]
