# Generated by Django 4.1.1 on 2022-09-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_article_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(upload_to='uploads/photos/', verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='first_image',
            field=models.ImageField(blank=True, upload_to='uploads/photos/'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='second_image',
            field=models.ImageField(blank=True, upload_to='uploads/photos/'),
        ),
    ]
